#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["structlog"]
# ///
"""Generate a complete .env file with secure secrets for Appsmith Docker Compose."""

import secrets
import string
import sys
from pathlib import Path

import structlog

logger = structlog.get_logger()

CHARSET = string.ascii_letters + string.digits


def gen_hex(n: int = 32) -> str:
    return secrets.token_hex(n)


def gen_alphanumeric(n: int = 24) -> str:
    return "".join(secrets.choice(CHARSET) for _ in range(n))


def build_env() -> str:
    return f"""# =============================================================================
# Appsmith Production Environment Variables
# =============================================================================
# Generated by generate-secrets.py — re-run to get new secrets.
# =============================================================================

# --- Image Versions -----------------------------------------------------------
APPSMITH_VERSION=latest
MONGO_VERSION=7.0
REDIS_VERSION=7-alpine

# --- Ports (bind to localhost if behind a reverse proxy) ----------------------
APPSMITH_HTTP_PORT=80
APPSMITH_HTTPS_PORT=443
APPSMITH_BIND=0.0.0.0

# --- Encryption (MUST be set for production - never change after first boot) --
APPSMITH_ENCRYPTION_PASSWORD={gen_hex()}
APPSMITH_ENCRYPTION_SALT={gen_hex()}

# --- MongoDB (internal - stores all Appsmith data) ----------------------------
MONGO_USER=appsmith
MONGO_PASSWORD={gen_alphanumeric()}
MONGO_DB=appsmith

# --- Redis (for caching/sessions) ---------------------------------------------
REDIS_PASSWORD={gen_alphanumeric()}
REDIS_MAXMEMORY=256mb
REDIS_MAXMEMORY_POLICY=allkeys-lru
APPSMITH_REDIS_URL=redis://:${{REDIS_PASSWORD}}@cache:6379
"""


def main() -> None:
    out = Path(__file__).parent / ".env"
    out.write_text(build_env())
    logger.info("env_generated", path=str(out))
    logger.info("review_needed", fields=[])


if __name__ == "__main__":
    try:
        main()
    except Exception:
        logger.exception("fatal")
        sys.exit(1)
